CREATE TABLE "public"."families" (
  "id"                bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "family_name"       character varying(150),
  "father_name"       character varying(100),
  "father_mobile"     character varying(20),
  "father_occupation" character varying(100),
  "mother_name"       character varying(100),
  "mother_mobile"     character varying(20),
  "mother_occupation" character varying(100),
  "guardian_name"     character varying(100),
  "guardian_mobile"   character varying(20),
  "guardian_relation" character varying(50),
  "email"             character varying(150),
  "address"           text,
  "city"              character varying(100),
  "state"             character varying(100),
  "pincode"           character varying(10),
  "created_at"        timestamp with time zone DEFAULT now(),
  "updated_at"        timestamp with time zone DEFAULT now(),
  CONSTRAINT "families_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."staff" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "staff_code"    character varying(50)    NOT NULL,
  "first_name"    character varying(100)   NOT NULL,
  "middle_name"   character varying(100),
  "last_name"     character varying(100),
  "date_of_birth" date,
  "gender"        character varying(20),
  "mobile"        character varying(20),
  "email"         character varying(150),
  "designation"   character varying(100),
  "department"    character varying(100),
  "joining_date"  date,
  "staff_type"    character varying(50),
  "address"       text,
  "city"          character varying(100),
  "state"         character varying(100),
  "pincode"       character varying(10),
  "profile_image" text,
  "is_active"     boolean                  DEFAULT true,
  "created_at"    timestamp with time zone DEFAULT now(),
  "updated_at"    timestamp with time zone DEFAULT now(),
  CONSTRAINT "staff_pkey" PRIMARY KEY (id),
  CONSTRAINT "staff_staff_code_key" UNIQUE (staff_code)
);

CREATE TABLE "public"."student_bank_details" (
  "id"                  bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "student_id"          bigint                   NOT NULL,
  "account_holder_name" character varying(150),
  "bank_name"           character varying(150),
  "account_number"      character varying(50),
  "ifsc_code"           character varying(20),
  "branch_name"         character varying(150),
  "created_at"          timestamp with time zone DEFAULT now(),
  "updated_at"          timestamp with time zone DEFAULT now(),
  CONSTRAINT "student_bank_details_pkey" PRIMARY KEY (id),
  CONSTRAINT "student_bank_details_student_id_key" UNIQUE (student_id)
);

CREATE TABLE "public"."student_class_details" (
  "id"                 bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "student_id"         bigint                   NOT NULL,
  "academic_year"      character varying(20)    NOT NULL,
  "class_name"         character varying(50)    NOT NULL,
  "section"            character varying(50),
  "joining_class"      boolean                  DEFAULT false,
  "roll_number"        character varying(30),
  "class_teacher_name" character varying(150),
  "created_at"         timestamp with time zone DEFAULT now(),
  "updated_at"         timestamp with time zone DEFAULT now(),
  CONSTRAINT "student_class_details_pkey" PRIMARY KEY (id),
  CONSTRAINT "unique_student_academic_year" UNIQUE (student_id, academic_year)
);

CREATE TABLE "public"."student_health" (
  "id"                       bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "student_id"               bigint                   NOT NULL,
  "blood_group"              character varying(10),
  "height_cm"                numeric(5,2),
  "weight_kg"                numeric(5,2),
  "medical_conditions"       text,
  "allergies"                text,
  "medications"              text,
  "emergency_contact_name"   character varying(150),
  "emergency_contact_number" character varying(20),
  "health_notes"             text,
  "created_at"               timestamp with time zone DEFAULT now(),
  "updated_at"               timestamp with time zone DEFAULT now(),
  CONSTRAINT "student_health_pkey" PRIMARY KEY (id),
  CONSTRAINT "student_health_student_id_key" UNIQUE (student_id)
);

CREATE TABLE "public"."student_hostel_details" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "student_id"     bigint                   NOT NULL,
  "academic_year"  character varying(20)    NOT NULL,
  "hostel_name"    character varying(150),
  "room_number"    character varying(50),
  "bed_number"     character varying(50),
  "hostel_type"    character varying(50),
  "joining_date"   date,
  "leaving_date"   date,
  "warden_name"    character varying(150),
  "warden_contact" character varying(20),
  "hostel_address" text,
  "status"         character varying(30)    DEFAULT 'ACTIVE'::character varying,
  "created_at"     timestamp with time zone DEFAULT now(),
  "updated_at"     timestamp with time zone DEFAULT now(),
  CONSTRAINT "student_hostel_details_pkey" PRIMARY KEY (id),
  CONSTRAINT "unique_student_hostel_year" UNIQUE (student_id, academic_year)
);

CREATE TABLE "public"."students" (
  "id"                        bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "mvaid"                     character varying(50)    NOT NULL,
  "family_id"                 bigint,
  "first_name"                character varying(100)   NOT NULL,
  "middle_name"               character varying(100),
  "last_name"                 character varying(100),
  "date_of_birth"             date,
  "section"                   character varying(50),
  "gender"                    character varying(20),
  "date_of_admission"         date,
  "joining_academic_year"     character varying(20),
  "academic_year"             character varying(20),
  "joining_class"             character varying(50),
  "class_residential_address" text,
  "pincode"                   character varying(10),
  "aadhaar_number"            character varying(20),
  "student_type"              character varying(30)    NOT NULL,
  "previous_school"           character varying(200),
  "nationality"               character varying(50),
  "staff_child"               boolean                  DEFAULT false,
  "caste_category"            character varying(100),
  "caste"                     character varying(100),
  "student_image"             text,
  "created_at"                timestamp with time zone DEFAULT now(),
  "updated_at"                timestamp with time zone DEFAULT now(),
  "email"                     text,
  "mobile"                    text,
  CONSTRAINT "students_mvaid_key" UNIQUE (mvaid),
  CONSTRAINT "students_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."students"
  ADD CONSTRAINT "fk_students_family" FOREIGN KEY (family_id) REFERENCES public.families(id);

ALTER TABLE "public"."student_bank_details"
  ADD CONSTRAINT "fk_student_bank_student" FOREIGN KEY (student_id) REFERENCES public.students(id);

ALTER TABLE "public"."student_class_details"
  ADD CONSTRAINT "fk_student_class_student" FOREIGN KEY (student_id) REFERENCES public.students(id);

ALTER TABLE "public"."student_health"
  ADD CONSTRAINT "fk_student_health_student" FOREIGN KEY (student_id) REFERENCES public.students(id);

ALTER TABLE "public"."student_hostel_details"
  ADD CONSTRAINT "fk_student_hostel_student" FOREIGN KEY (student_id) REFERENCES public.students(id);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."families" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."staff" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."student_bank_details" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."student_class_details" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."student_health" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."student_hostel_details" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."students" TO "anon", "authenticated", "postgres", "service_role";

