ALTER TABLE "public"."student_health"
  DROP CONSTRAINT "fk_student_health_student";

DROP TABLE "public"."student_health";

CREATE TABLE "public"."studets_health" (
  "id"                       bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."student_health_id_seq") NOT NULL,
  "student_id"               bigint                   NOT NULL,
  "blood_group"              character varying(10),
  "height_cm"                numeric(5,2),
  "weight_kg"                numeric(5,2),
  "medical_conditions"       text,
  "allergies"                text,
  "medications"              text,
  "emergency_contact_name"   character varying(150),
  "emergency_contact_number" character varying(20),
  "health_notes"             text,
  "created_at"               timestamp with time zone DEFAULT now(),
  "updated_at"               timestamp with time zone DEFAULT now(),
  CONSTRAINT "student_health_pkey" PRIMARY KEY (id),
  CONSTRAINT "student_health_student_id_key" UNIQUE (student_id)
);

ALTER TABLE "public"."studets_health"
  ADD CONSTRAINT "fk_student_health_student" FOREIGN KEY (student_id) REFERENCES public.students(id);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."studets_health" TO "anon", "authenticated", "postgres", "service_role";
